{
	{
		"Categoria":"Marketing",
		"Tags":"Material, bexiga, pixels, onlife",
		"País":"JAP",
		"Empresa":"Yasuaki Kakehi",
		"APP":"BelliesWave",
		"Entrega":"Um material de borracha que muda de cor utilizando o sistema de pixels no ambiente offline",
		"Diferencial":"O material de borracha muda de cor conforme a bexiga é inflada. As bexigas possuem um sistema de pixels sobrepostos e, sem necessidade de energia, mudam de cor. Indicado para displays.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"",
		"Produtos":"X",
		"Site":"http://www.jst.go.jp/erato/kawahara"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"Gadget",
		"País":"EUA",
		"Empresa":"Widevantage",
		"APP":"Widevantage",
		"Entrega":"Uma caneta para iPad que não usa bluetooth e nem bateria, com aplicações para crianças.",
		"Diferencial":"Não usa baterias ou bluetooth",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.widevantage.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"Led, Iluminação",
		"País":"JAP",
		"Empresa":"White",
		"APP":"Ilumicap",
		"Entrega":"Copo com led comandado pelo celular",
		"Diferencial":"O copo tem um led colorido que responde aos comandos do app instalado no celular.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.illumicap.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"headphone, inteligente , AI, experiência",
		"País":"EUA",
		"Empresa":"Vinci",
		"APP":"Vinci",
		"Entrega":"Um headphone inteligente que responde a comandos de voz",
		"Diferencial":"O headphone possui sistema de inteligência artificial possibilitando ao usuário uma nova experiência de usabilidade. Todos os comandos são realizados por comando de voz e ele pode realizar tarefas como simplesmente trocar uma música ou até pedir direções de gps para o headphone.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"en.vinci.im"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"Fumo, inovação, cool stuff",
		"País":"EUA",
		"Empresa":"Vaportronix",
		"APP":"VQ by Vaportronix",
		"Entrega":"Um vaporizador que fica acoplado na capinha do celular",
		"Diferencial":"O vaporizador VQ vem acoplado à capinha de celular facilitando o transporte e deixando-o mais discreto para os fumantes",
		"B2B":"",
		"B2C":"",
		"Serviços":"",
		"Produtos":"",
		"Site":"www.vqaze.com"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"Game, comando de voz, tecnologia, inclusão social, gamification",
		"País":"JAP",
		"Empresa":"Tongullman",
		"APP":"Ton Ton Voice Sumo",
		"Entrega":"Jogo de sumô onde os bonecos são movidos por comando de voz",
		"Diferencial":"A empresa desenvolve produtos voltados para tecnologia e um dos segmentos é a exploração do comando de voz. O jogo é um tabuleiro onde dois jogadores possuem bonecos de sumô e o movimento deles se dá a partir do maior número de TONTON ditos pelo jogador. Quanto mais rápido ele for, maior será a chance dele ganhar. O dispositivo é utilizado também para tratamento de pessoas com problema nas cordas vocais.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"https://tongullman.co.jp/index.php"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Marketing, Target, Instrucional, Vendas.",
		"País":"JAP",
		"Empresa":"Talking POP",
		"APP":"Talking POP",
		"Entrega":"Dispositivo de interação entre clientes e produtos",
		"Diferencial":"Os produtos ficam em um lugar com o dispositivo e quando o cliente pega aquele produto na mão ele recebe informações em tempo real por voz. O alerta pode ser customizado por peso, luz, tipo de movimento, som, etc.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"X",
		"Site":"www.i-studio.co.jp/en"
	},
	{
		"Categoria":"Inclusão social",
		"Tags":"inclusão social, engajamento, socialização, conscientização",
		"País":"EUA",
		"Empresa":"Stacha",
		"APP":"Stacha Stuttering",
		"Entrega":"Coleira eletrônica que imita gagueira",
		"Diferencial":"A coleira emite um sinal na garganta para simular gagueira no intiuto de engajar a sociedade e entendimento de como essa deficiência é dificil de lidar.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.ourstacha.com"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"som, movimento, luz, controle, sensor, cool stuff",
		"País":"JAP",
		"Empresa":"Sony",
		"APP":"Motion Sonic",
		"Entrega":"Pulseira de som e luz que se propagam de acordo como movimento",
		"Diferencial":"A pulseira tem um sensor de movimento que possibilita criar sons para performances de dança e apresentacões de karatê, por exemplo. É possível também controlar uma música que está sendo tocada com o movimento da pulseira",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"motionsonic.sony"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"aroma difusor, inteligente, personalizado, cool stuff",
		"País":"JAP",
		"Empresa":"Shiseido",
		"APP":"Bliscent",
		"Entrega":"Um aroma difusor inteligente",
		"Diferencial":"O amora difusor traz cheiros personalizados para o ambiente de acordo com os batimentos cardíacos de quem está no espaço para assim atingir o melhor estado mental para o usuário",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.bliscent.net"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"cerveja, fabricação, maker,",
		"País":"EUA",
		"Empresa":"PicoBrew",
		"APP":"PicoBrew",
		"Entrega":"Empresa especializada em fazer máquinas para criar cerveja artesanal de modo fácil.",
		"Diferencial":"A PicoBrew foi feita para quem quer fazer cerveja artesanal em casa de maneira fácil em casa. A promessa é de que a cerveja vai ficar boa desde a primeira produção.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.picobrew.com"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"Marketing, PDV, Cool stuff, Painel, offline",
		"País":"EUA",
		"Empresa":"Oat Foundry",
		"APP":"Split Flap",
		"Entrega":"Uma oficina de coisas legais. Desde o painel interativo apresentado no SXSW até demandas personalizadas",
		"Diferencial":"O Split Flap é um painel nostálgico para bares, restaurantes, aeroportos. Imitando os paineis antigos de aeroporto, é possível personalizar mensagens para o público, tudo de forma digital com conectividade de USB e bluetooth, por exemplo.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.oatfoundry.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Target, Marketing, reconhecimento digital, identificação de produto, experiência, database, informação",
		"País":"EUA",
		"Empresa":"NTT DATA",
		"APP":"Talking Beer",
		"Entrega":"Um sinal digital interativo que automaticamente reconhece a marca do produto que a pessoa está segurando na mão ou vestindo.",
		"Diferencial":"O sinal pode ser programado para identificar um produto na mão ou que a pessoa está vestindo. Dessa forma é possível criar experiências para esse usuário totalmente personalizadas. O programa ainda compila todas as informações obtidas criando assim um database sobre cada usuário para customizar cada experiência para ele.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.nttdata.com"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"comando de voz, inteligente, conversor, cool stuff",
		"País":"JAP",
		"Empresa":"NeuroVoice",
		"APP":"NeuroVoice",
		"Entrega":"Software que converte a voz do usuário na voz de qualquer outro usuário",
		"Diferencial":"O software utiliza o comando de voz para mudar a voz do usuário em vozes famosas como Michael Jackson, Hillary Cliton, Will Smith, Taylor Swift, etc.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.neurovoice.jp"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"esporte, meditação, EAD",
		"País":"EUA",
		"Empresa":"Moment Meditation",
		"APP":"Moment Meditation",
		"Entrega":"Um site com aulas de meditação.",
		"Diferencial":"O site possui várias classes onde pode-se encontrar aulas de meditação guiada para vários tipos de situação como 'busca pela felicidade', 'foco'e 'calma'.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.momentmeditation.com"
	},
	{
		"Categoria":"Business",
		"Tags":"Empresa, colaboração, funcionários, network, engajamento, eficiência,",
		"País":"EUA",
		"Empresa":"Magency",
		"APP":"Magency",
		"Entrega":"Plataforma pensada para criar aproximação e engajamento de colaboradores e funcionários buscando maior eficiência na comunicação e feed backs.",
		"Diferencial":"A plataforma dá a possibilidade de criar feed backs para as pessoas preencherem após reuniões, seminários e convenções, cursos e treinamento, marcar workshops e reuniões, etc. A colaboração do funcionário para melhorias de todos os processos e conteúdos fica mais acessível a todos.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"magency.me"
	},
	{
		"Categoria":"Conteúdo",
		"Tags":"VR, 360, conteúdo, video, AR",
		"País":"JAP",
		"Empresa":"Kids Plates",
		"APP":"Kids Plates",
		"Entrega":"Empresa japonesa que cria conteúdos de VR, AR, vídeos 360, etc",
		"Diferencial":"Empresa japonesa que cria conteúdos de VR, AR, vídeos 360, etc. Um dos produtos de destaque é o DOLLY360, um robô com camera 360 acoplada para chegar em ambientes fechados, de difícil acesso em grande velocidade ou não",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.kidsplates.jp"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"VR, realidade mista, educação, diversão",
		"País":"JAP",
		"Empresa":"Invisible Force - Psychic Demo",
		"APP":"HoloLens",
		"Entrega":"Óculos de realidade mista, utilizado para brincar ou aprender.",
		"Diferencial":"Um óculos que possibilita as pessoas interagirem virtualmente com objetos reais ou criar objetos e cenários fictícios para interagir com eles. Exemplo: professores criam conteúdos para ensinar matérias aos alunos virtualmente, aproximando-os ainda mais do conteúdo real",
		"B2B":"X",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"X",
		"Site":"www.i-studio.co.jp/en"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"musica, gravação, estúdio, facilitador,",
		"País":"EUA",
		"Empresa":"HumON",
		"APP":"HumON",
		"Entrega":"Um aplicativo para gravar músicas de forma fácil com o smartphone.",
		"Diferencial":"O aplicativo capta o som e traduz a melodia em cifras. Além de gravar ele possibilita editar a música, tem sistema de gravação de alta qualidade e também permite que o usuário utilize timbres de voz para criar músicas.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"http://www.hum-on.com"
	},
	{
		"Categoria":"Sustentabilidade",
		"Tags":"Tecnologia, tecido, vestuário",
		"País":"EUA",
		"Empresa":"Horvath",
		"APP":"Horvath",
		"Entrega":"Tecido que não precisa de lavagem constante",
		"Diferencial":"A Hovarth desenvolveu um tecido que não suja com facilidade e não tem necessidade de muitas lavagens, possibilitando que a pessoa utilize a mesma roupa várias vezes.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"horvathco.com"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"espelho, tecnologia, database, informação",
		"País":"EUA",
		"Empresa":"Hi Mirror",
		"APP":"Hi Mirror",
		"Entrega":"Um espelho digital que armazena dados sobre a pele do usuário",
		"Diferencial":"O espelho tira uma foto do rosto da pessoa todos os dias e armazena os dados de evolução da epiderme do usuário que pode acessar no celular sempre que quiser.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"X",
		"Site":"www.himirror.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"robo, inteligente, automação, casa, inteligencia artificial,",
		"País":"EUA",
		"Empresa":"Hey Kuri",
		"APP":"Kuri",
		"Entrega":"Um robô doméstico inteligente",
		"Diferencial":"O robô aprende com as pessoas, entende o plano de chão da casa/apartamento rapidamente, demonstra emoções, conversa. Um robô que tem personalidade de gente. Os ",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.heykuri.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"inclusão social, engajamento, cool stuff, automação, comando de voz,",
		"País":"JAP",
		"Empresa":"Hakuhodo",
		"APP":"Jins Meme",
		"Entrega":"Óculos inteligente que possibilita utilizar produtos eletrônicos e aplicativos utilizando apenas o olho",
		"Diferencial":"Possui muitas funcionalidades legais como tocar músicas sem tocar no celular, tirar uma foto sem as mãos, etc. A usabilidade mais incrível é para pessoas com Doença de Lou Gehrig por exemplo, que perdem o controle do sistema nervoso perdendo assim os movimentos.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.jins.com/us"
	},
	{
		"Categoria":"Pets",
		"Tags":"pet, pet toy, interativo, tecnologia",
		"País":"EUA",
		"Empresa":"Gomi Labs",
		"APP":"Gomi",
		"Entrega":"Uma bolinha para cachorro interativa que armazena dados e personaliza brincadeiras.",
		"Diferencial":"A bolinha armazena os padrões de brincadeira do cachorro e personaliza brincadeiras para ele. Ela muda de cor para manter o engajamento do pet. Ela é conectada a um smartwatch que possibilita com que o dono do pet interaja com ele mesmo estando longe.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.gomilabs.io"
	},
	{
		"Categoria":"Logística",
		"Tags":"Comida, inteligencia artificial, database, entrega, delivery, saúde,",
		"País":"EUA",
		"Empresa":"Game Changer CATAPULT",
		"APP":"BENTO",
		"Entrega":"Um serviço de entrega de comida em escritórios e dicas de saúde para os usuários",
		"Diferencial":"Totalmente automatizado, o serviço inclui criação de cardápio personalizado de acordo com os dados coletados dos usuários, o pagamento é feito automaticamente na plataforma, sugestão de menus além de dicas de saúde personalizada para cada indivíduo de acordo com seu histórico de pedidos. Praticamente um conselor de saúde e alimentação.",
		"B2B":"X",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"gccatapult.panasonic.com/en/bento/"
	},
	{
		"Categoria":"Esporte",
		"Tags":"Esporte, informação",
		"País":"JAP",
		"Empresa":"Fukushima Wheel",
		"APP":"Fukushima Wheel",
		"Entrega":"Sensores para instalar na bicicleta que trazem informações sobre tempo e condições ambientais",
		"Diferencial":"O sensor é instalado na roda da bicicleta e a partir dele é possível ter acesso a informações de temperatura, CO, radiação, condições climáticas, etc. O sinal é enviado para o smartphone que coleta a informação.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.fukushimawheel.org"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"Funeral, interativo, video, cool stuff",
		"País":"EUA",
		"Empresa":"Fragment",
		"APP":"Fragment",
		"Entrega":"App que junta fotos e momentos de alguém que morreu para fazer um video de homenagem. Funeral online",
		"Diferencial":"O Fragment possibilita que os familiares e amigos de alguém que morreu se conectem e façam upload de fotos e momentos especiais e atomaticamente o app cria um video em homenagem a esta pessoa que morreu.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.fragment.life"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"conexão, legado, rede social,",
		"País":"EUA",
		"Empresa":"Final Thoughts",
		"APP":"Final Thoughts",
		"Entrega":"Uma rede onde as pessoas postam momentos especiais da vida que serve como um diário e histórico de tudo que a pessoa fez.",
		"Diferencial":"Com foco em criar um legado de cada pessoa, o Final Thoughts além de conectar pessoas tem funcinalidade de ",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.finalthoughts.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Marketing, Target, Reconhecimento Facial.",
		"País":"EUA",
		"Empresa":"Face Targeting AD",
		"APP":"FACE TARGETING AD",
		"Entrega":"Encontra o produto certo para o usuário",
		"Diferencial":"Utilizando o reconhecimento facial, o app mostra para a pessoa o produto ou serviço ideal para ela levando em consideração a idade, o sexo, as características faciais e emoções do usuário. Desenvolvido pela Microsoft Cognitive Services.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"http://suda-lab.jp/face"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"óculos, interativo, personalização",
		"País":"EUA",
		"Empresa":"Chemi-ON",
		"APP":"Chemi-ON",
		"Entrega":"Óculos com visor interativo que é possível criar palavras, formas e desenhos na lente digitalmente",
		"Diferencial":"O óculos é interligado com um aplicativo de celular onde é possível criar uma personalização de mensagens e fotos para aparecer na lente.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.chemi-on.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"inovacão, venda, experiência",
		"País":"EUA",
		"Empresa":"Carvana",
		"APP":"Car Vending Machine",
		"Entrega":"Uma vending machine de carros!",
		"Diferencial":"A Carvana propõe uma nova forma de comércio de carros e automóveis: com uma vending machine. Os carros ficam expostos na máquina e toda a compra é realizada virtualmente. Para retirar o produto, o cliente recebe uma moeda para inserir na vending machine e retirar seu produto, um carro.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.carvana.com"
	},
	{
		"Categoria":"Saúde",
		"Tags":"saúde, tratamento,",
		"País":"JAP",
		"Empresa":"Booster Parco",
		"APP":"Neko Electro",
		"Entrega":"Uma tiara que informa quando a pessoa está com a postura errada",
		"Diferencial":"A tiara vibra toda vez que o usuário está com postura errada podendo trazer danos para a coluna. Utilizado no tratamento de escoleose e outras variações da doença.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.booster-parco.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"automação, casa, armário,",
		"País":"JAP",
		"Empresa":"Booster Parco",
		"APP":". + Move",
		"Entrega":"Cabideiro que gira para facilitar a escolha de roupa.",
		"Diferencial":"O cabideiro tem um sistema giratório que faz com que as roupas vão passando na frente do usuário como uma vitrine facilitando a busca e escolha da roupa certa.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.booster-parco.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"show, som, musica, personalização, cool stuff",
		"País":"EUA",
		"Empresa":"Augmented Acoustics",
		"APP":"Supra Live",
		"Entrega":"Um dispositivo que permite o usuário personalizar o som de um show e ouvir em seu fone de ouvido",
		"Diferencial":"O dispositivo tem corretor de acústica e possibilita que o usuário seja seu próprio engenheiro de som em um show. É possível corrigir irregularidades e acrescentar efeitos no som que o dispositivo capta",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"augmentedacoustics.com"
	},
	{
		"Categoria":"Conteúdo",
		"Tags":"video, interativo",
		"País":"EUA",
		"Empresa":"Wirewax",
		"APP":"Wirewax",
		"Entrega":"Empresa especializada em criar vídeos interativos",
		"Diferencial":"Os videos produzidos pela Wirewax contém tags e botões que possibilitam interagir com o vídeo ao vivo.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.wirewax.com"
	},
	{
		"Categoria":"Sustentabilidade",
		"Tags":"vr, óculos, tecnologia, low cost, energia free",
		"País":"EUA",
		"Empresa":"Widevantage",
		"APP":"Widevantage",
		"Entrega":"Laboratório que fornece óculos VR para acoplar em um celular mas o óculos não precisa de energia,",
		"Diferencial":"Um óculos que foi feito para conteúdo VR em smartphones e o diferencial é que o óculos não precisa de energia para realizar nenhuma funcionalidade.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.widevantage.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"VR, low cost",
		"País":"JAP",
		"Empresa":"White",
		"APP":"Milbox",
		"Entrega":"Caixa de papelão que vira um óculos de VR com um smartphone acoplado",
		"Diferencial":"Caixa de papelão que vira um óculos de VR com um smartphone acoplado",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"milbox.tokyo"
	},
	{
		"Categoria":"Esporte",
		"Tags":"",
		"País":"JAP",
		"Empresa":"Trek Track",
		"APP":"Trek Track",
		"Entrega":"Dispositivo para encontrar pessoas que estão escalando em montanhas.",
		"Diferencial":"O dispositivo tem bateria que dura até 5 dias e serve para que os usuários não se percam em trilhas e escaladas. Ele grava os movimentos do usuário a cada 30 segundos, e também possui um botão para pedir socorro caso esteja em perigo",
		"B2B":"X",
		"B2C":"",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.i-studio.co.jp/en"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"energia, economia, engajamento, conexão,",
		"País":"EUA",
		"Empresa":"Stratis",
		"APP":"Stratis",
		"Entrega":"Permite ao usuário acesso fácil, rápido e conveniente a acesso móvel, controle de energia e automação para suas unidades.",
		"Diferencial":"O sistema interliga pessoas, empresas, casas, prédios para buscar economia de energia. O sistema armazena informações a fim de gerar esta economia.",
		"B2B":"X",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"stratisems.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"automação, casa,",
		"País":"EUA",
		"Empresa":"Somfy Group",
		"APP":"Neocontrol",
		"Entrega":"Sistema de automação para casa.",
		"Diferencial":"com o Neocontrol é possível automatizar e sincronizar aparelhos digitais em casa. Possibilita criar ambientações com iluminações diferentes, acesso remoto de qualquer item interligado ao sistema.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.neocontrolglobal.com"
	},
	{
		"Categoria":"Conteúdo",
		"Tags":"360, conteúdo",
		"País":"BRA",
		"Empresa":"Shots360",
		"APP":"Shots360",
		"Entrega":"Criação de conteúdos com câmeras 360",
		"Diferencial":"Empresa brasileira produtora de conteúdos com câmera em 360 graus",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.shots360.com.br"
	},
	{
		"Categoria":"Marketing",
		"Tags":"AR, marketing, produção, jogo",
		"País":"EUA",
		"Empresa":"Seek Adventure App",
		"APP":"Seek Adventure App",
		"Entrega":"Empresa que cria jogos de realidade aumentada para campanhas.",
		"Diferencial":"A empresa cria conteúdos de realidade aumentada para empresas. As empresas podem criar seu próprio jogo de realidade aumentada para criar campanhas de engajamento do consumidor.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.seekadventureapp.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Marketing, PDV, Cool stuff",
		"País":"BRA",
		"Empresa":"Robozão",
		"APP":"Robozão",
		"Entrega":"Uma fantasia de robô para ações de marketing",
		"Diferencial":"A fantasia possui espaços dedicados à exposição de marcas para ações de live marketing",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.robozaousa.com"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"multimídia, video, musica, mensagem, conexão",
		"País":"EUA",
		"Empresa":"Rave",
		"APP":"Rave",
		"Entrega":"Um sistema de mensagem multimídia onde o usuário pode assistir vídeos, ouvir música e tocar mensagem simultaneamente.",
		"Diferencial":"Um sistema de mensagem multimídia onde o usuário pode assistir vídeos, ouvir música e tocar mensagem simultaneamente.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"rave.io"
	},
	{
		"Categoria":"Cool stuff",
		"Tags":"tampão, anti ruído,",
		"País":"EUA",
		"Empresa":"QuietON",
		"APP":"QuietON",
		"Entrega":"Um tampão anti ruído que combina cancelamento de ruído e atenuação de ruído acústico para criar silêncio",
		"Diferencial":"Um tampão anti ruído que combina cancelamento de ruído e atenuação de ruído acústico para criar silêncio",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"quieton.com"
	},
	{
		"Categoria":"Sustentabilidade",
		"Tags":"Monitoramento, compartilhamento, social, cidadania, target, governo, engajamento",
		"País":"Indonésia",
		"Empresa":"Qlue",
		"APP":"Qlue",
		"Entrega":"Aplicativo de engajamento civil colaborativo para governo, cidadãos, empresas, etc.",
		"Diferencial":"O aplicativo serve para que as pessoas compartilhem informações sobre seus bairros, problemas que a cidade enfrenta, novas oportunidades de negócios na cidade, reclamações, sugestões, etc. A extensão Qlue MyCity cria um database de informações sobre a cidade para governos e empresas terem uma clareza maior sobre o território onde atuam.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"qlue.co.id"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"VA, smartglasses",
		"País":"JAP",
		"Empresa":"QDLaser",
		"APP":"Retíssa",
		"Entrega":"Dispositivo de realidade aumentada",
		"Diferencial":"O Retíssa é um óculos de realidade aumentada que conta com um projeto que lança o conteúdo direto para a retina do usuário.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.qdlaser.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Chatbot, sac, atendimento, marketing",
		"País":"BRA",
		"Empresa":"Overmedia Cast",
		"APP":"Overmedia Cast",
		"Entrega":"Empresa cria chat bots para Santander e Telefonica",
		"Diferencial":"Os Chatbots fazem atendimento aos clientes, apresentam novas oportundades de produtos e planos além de trazer uma dinâmica mais fluída para o usuário",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.overmediacast.com"
	},
	{
		"Categoria":"Estudo",
		"Tags":"Estudo espacial, universo, sustentabilidade",
		"País":"EUA",
		"Empresa":"NASA",
		"APP":"GRACE",
		"Entrega":"GRACE - Estudo sobre a Terra no decorrer dos anos",
		"Diferencial":"A GRACE foi lançada ao espaço em 2002 e mostra a evolução da gravidade na Terra bem como os impactos ambientais acarretados ao longo dos anos que está em órbita",
		"B2B":"X",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.nasa.gov"
	},
	{
		"Categoria":"Sustentabilidade",
		"Tags":"material, couro, bolsas, produto",
		"País":"BRA",
		"Empresa":"Mole Bags",
		"APP":"Mole Bags",
		"Entrega":"Bolsas e produtos de couro maleável",
		"Diferencial":"O couro especial é mais maleável que o normal, possibilitando a marca trabalhar melhor com o material criando bolsas diferentes",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.molebags.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"hi-tech, drone, desenvolvimento",
		"País":"EUA",
		"Empresa":"Mohyi Labs",
		"APP":"Mohyi Labs",
		"Entrega":"Desenvolvimento de drones de alta performance",
		"Diferencial":"O Mohyi Labs é um laboratório de tecnologia que hoje está focado em desenvolver drones de ponta, seja na questão do design como da performance",
		"B2B":"X",
		"B2C":"",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.mohyilabs.com"
	},
	{
		"Categoria":"Business",
		"Tags":"Conectar pessoas, networking, coworking, profissional, estratégia, especialista, target",
		"País":"EUA",
		"Empresa":"Mod Squad",
		"APP":"Mod Squad",
		"Entrega":"Uma plataforma que encontra profissionais especialistas em determinados assuntos para trabalhar junto com empresas que precisam da ajuda desses profissionais.",
		"Diferencial":"Parecido com o método Plug and Play da Tudo, a plataforma busca conectar profissionais especialistas em determinados assuntos com empresas que precisam desses especialistas para um determinado trabalho. Busca encontrar o profissional certo para atender à demanda do trabalho a ser realizado. Possui uma rede com mais de 10 mil profissionais disseminados em mais de 70 países ao redor do mundo",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.modsquad.com"
	},
	{
		"Categoria":"Conteúdo",
		"Tags":"conteúdo, digital, 3d, vr, ar, realidade mista, experiência, marketing",
		"País":"BRA",
		"Empresa":"Mob Content",
		"APP":"Mob Content",
		"Entrega":"Empresa especializada em criar conteúdos de experiência de segunda tela.",
		"Diferencial":"Empresa especializada em criar conteúdos de experiência de segunda tela.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.mobcontent.co"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"VR, óculos, realidade mista, tecnologia, low cost, facilitador",
		"País":"BRA",
		"Empresa":"Loox VR",
		"APP":"Loox VR",
		"Entrega":"A empresa cria óculos de realidade virtual e realidade mista a preço baixo",
		"Diferencial":"A empresa cria conteúdos e vende óculos de VR e realidade mista de forma democrática, com preço baixo para distribuição em massa. Possui vários modelos alternativos para que sejam barateados.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"X",
		"Site":"www.looxvr.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"video, 4k, hd, marketing, publicidade, conteúdo",
		"País":"EUA",
		"Empresa":"LemonLight",
		"APP":"LemonLight",
		"Entrega":"Criação de videos em HD para ações e campanhas publicitárias",
		"Diferencial":"Criação de videos em HD para ações e campanhas publicitárias",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.lemonlight.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"Tecnologia, interação",
		"País":"BRA",
		"Empresa":"Lemonade",
		"APP":"Lemonade",
		"Entrega":"Empresa brasileira que cria projetos inovadores, baseados nas mais avançadas tecnologias de interação.",
		"Diferencial":"Esse ano a Lemonade lançará o Lemonade App, um hub de interação em forma de aplicativo e plataforma mobile, que permitirá eliminar as fronteiras entre conteúdos e experiências em ações que potencializam todos os recursos de um smartphone, unindo os universos físico e digital.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.lemonadeapp.com"
	},
	{
		"Categoria":"Business",
		"Tags":"moda, serviço, target, comécio, empreendedorismo",
		"País":"Indonésia",
		"Empresa":"Kostoom",
		"APP":"Kostoom",
		"Entrega":"Uma plataforma para designers de roupas e profissionais de costura se conectarem com clientes.",
		"Diferencial":"Trata-se de um grande hub de moda e custura onde as pessoas da área podem fazer sua própria produção de roupa para vender online no Kostoom sem sair de casa. A plataforma é praticamente um ",
		"B2B":"X",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.kostoom.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"AV, Realidade mista, smartglasses",
		"País":"JAP",
		"Empresa":"Kobe Digital Labo",
		"APP":"Kobe Digital Labo",
		"Entrega":"Desenvolvimento de tecnologia smartglass",
		"Diferencial":"A empresa japonesa desenvolve tecnologia de smartglass para vários segmentos como cursos e treinamentos, experiência, games, etc.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"",
		"Produtos":"X",
		"Site":"kobedigitallabo.github.io"
	},
	{
		"Categoria":"Business",
		"Tags":"Solução Empresarial, colaboração, escritório, RH, noas ideias, pesquisa, brainstorm, acompanhamento, avaliação",
		"País":"EUA",
		"Empresa":"Klaxoon",
		"APP":"Klaxoon",
		"Entrega":"A plataforma serve para gerar mais interação entre equipes e profissionais de uma mesma empresa",
		"Diferencial":"Oferece a possibilidade da empresa criar grupos, debates, engajamento de seus funcionários. Visando a eficiência da colaboração nas empresas, o Klaxoon serve para conectar pessoas, ideias, ferramentas, trazer pesquisas internas e tudo fica exibido em uma timeline para acompanhamento e avaliação.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.klaxoon.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Marketing, Target, branding, VR, conceito visual, publicidade",
		"País":"EUA",
		"Empresa":"Killer Infographics",
		"APP":"Killer Infographics",
		"Entrega":"Uma agência que utiliza a comunicação visual estrategicamente para chamar a atenção e criar engajamento dos usuários",
		"Diferencial":"A empresa cria soluções estratégicas utilizando o conceito visual. Oferecem soluçõe que vão do branding ao conteúdo de VR e realidade aumentada. Além de aumentar a diversidade da audiência, a promessa é manter a perenidade da marca após a interação do público.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.killerinfographics.com"
	},
	{
		"Categoria":"Business",
		"Tags":"Cultura local, cosmopolitanismo, e-commerce",
		"País":"BRA",
		"Empresa":"Japonique",
		"APP":"Japonique",
		"Entrega":"Comércio de produtos japoneses em São Paulo",
		"Diferencial":"Um site especializado em itens de cultura japonesa e oriental na cidade de São Paulo. Entregam com bicicletas na cidade.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.japonique.com"
	},
	{
		"Categoria":"Esporte",
		"Tags":"Esporte, database, sensor, informação",
		"País":"EUA",
		"Empresa":"Interactive Shoes Hub",
		"APP":"Interactive Shoes Hub",
		"Entrega":"Um sensor colocado nos tênis para coletar dados sobre os usuários.",
		"Diferencial":"Os sensores captam os movimentos do usuários e armazenam esses dados em um grande database. A informação coletada vai desde o movimento realizado pelo usuário até seu trajeto e isso é disponibilizado para ele no app.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"interactive-shoes-hub.com"
	},
	{
		"Categoria":"Conteúdo",
		"Tags":"VR, marketing, business, empesa, facilitador, low cost,",
		"País":"EUA",
		"Empresa":"InstaVR",
		"APP":"InstaVR",
		"Entrega":"Uma plataforma para criar conteúdo de VR em minutos e com preço baixo",
		"Diferencial":"A empresa traz uma solução em cima do conteúdo de VR onde empresas e pessoas podem criar seu próprio conteúdo de VR em pouco tempo e a low cost",
		"B2B":"X",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.instavr.co"
	},
	{
		"Categoria":"Social",
		"Tags":"rede social, network, interesse, conexão",
		"País":"EUA",
		"Empresa":"Inner Circle",
		"APP":"Inner Circle",
		"Entrega":"Rede social que conecta as pessoas com interesses em comum.",
		"Diferencial":"A rede tem um perfil simplificado sobre informações que realmente interessam às pessoas e indica amizades de pessoas com interesses em comum.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"https://www.theinnercircle.co/"
	},
	{
		"Categoria":"Evento",
		"Tags":"Eventos, aplicativo, interação, engajamento, planejamento, integração, facilitador",
		"País":"EUA",
		"Empresa":"InEvent",
		"APP":"InEvent",
		"Entrega":"Serviço para programar um evento, englobando praticamente todas as principais features para a realização do evento.",
		"Diferencial":"Soluções integradas para a realização do evento, incluindo: check in, RSVP, app mobile, ativações, criação de database do evento, grandes telas, iBEacons, mapas de conexão, cobertura ao vivo, relatórios, etc. Todos integrados entre si.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.inevent.us"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"rádio, captador, conversor.",
		"País":"EUA",
		"Empresa":"Hint",
		"APP":"Hint",
		"Entrega":"Um conversor de sinal analógico de rádio que transmite para várias fontes digitais que propagam o som",
		"Diferencial":"O captador coleta as ondas de rádio FM e traduz para smartphones e devices que acessam essas ondas por meio de uma URL enviada do captador para as fontes de propagação de som.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"NT"
	},
	{
		"Categoria":"Business",
		"Tags":"Empresa, colaboração, funcionários, network, engajamento, eficiência,",
		"País":"Indonésia",
		"Empresa":"Happy5",
		"APP":"Happy5",
		"Entrega":"Plataforma pensada para criar aproximação e engajamento de colaboradores e funcionários buscando maior eficiência na comunicação e feed backs.",
		"Diferencial":"A plataforma tem funcionalidade de aproximar os funcionários e facilitar a comunicação oferecendo espaço para conversas, definição de metas trimestrais para um grupo ou indivíduo, análise do progresso de cada tarefa e dá feedback sobre cada feature da plataforma.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.happy5.co"
	},
	{
		"Categoria":"Pets",
		"Tags":"pet, rede social, profissional, empresas, pessoas, serviços, petshop",
		"País":"Coreia",
		"Empresa":"Happy Puppy",
		"APP":"Happy Puppy",
		"Entrega":"Rede Social relacionada aos bichos de estimação",
		"Diferencial":"Oferece a possibilidade de encontrar veterinários, pessoas doando cachorros, interessados em adotar, pet shop, vendas de produtos, etc",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"https://itunes.apple.com/br/app/happy-puppy-free-game-app/id1106603823?mt=8"
	},
	{
		"Categoria":"Sustentabilidade",
		"Tags":"Economia colaborativa",
		"País":"JAP",
		"Empresa":"Hackist",
		"APP":"RePHub",
		"Entrega":"Um hub de reforma de produtos que as pessoas não usam mais para doar para outras pessoas",
		"Diferencial":"O problema de lixo no Japão é algo recorrente e uma solução para isso foi criar uma plataforma para conectar pessoas que possuem objetos que não estão mais usando ou precisam de reforma para doar para outras que estão procurando esses produtos como Guarda-chuvas, carrinho de bebê, etc. Solução para a cidade de Tóquio",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"http://hackist.jp/rephub/en/"
	},
	{
		"Categoria":"Turismo",
		"Tags":"Informação, turismo, viagem, cultura, cegos.",
		"País":"JAP",
		"Empresa":"Hackist",
		"APP":"Project JACH",
		"Entrega":"Dispositivo que traz informações sobre os locais turísticos do Japão",
		"Diferencial":"Basta ligar o fone onde a pessoa estiver para receber conteúdos e experiências legais sobre os locais mais visitados do Japão.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"X",
		"Site":"http://hackist.jp/jach/"
	},
	{
		"Categoria":"Logística",
		"Tags":"Transporte, carona, logística, entrega, delivery",
		"País":"Indonésia",
		"Empresa":"Go-Jek",
		"APP":"Go-Jek",
		"Entrega":"O ",
		"Diferencial":"Um site que conecta os motociclistas da indonésia com pessoas que precisam do serviço. Oferecem 14 tipos de serviço que vão desde entrega até transporte público, serviços logísticos, etc. A empre",
		"B2B":"X",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"go-jek.com"
	},
	{
		"Categoria":"Business",
		"Tags":"Empresa, colaboração, funcionários, network, engajamento, eficiência,",
		"País":"BRA",
		"Empresa":"Flock",
		"APP":"Flock",
		"Entrega":"Uma plataforma que conecta funcionários e facilita a comunicação",
		"Diferencial":"O Flock é uma plataforma que conecta as pessoas dentro da empresa para interação dinâmica e trazer maior engajamento dos indivíduos. Uma feature importante é a possibilidade de realizar reuniões virtuais, criar grupos privados e públicos, interagir com pessoas de fora da empresa como fornecedores e verificar o histórico de tudo que acontece.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.flock.co"
	},
	{
		"Categoria":"Evento",
		"Tags":"Evento, planejamento, conectar pessoas,",
		"País":"EUA",
		"Empresa":"Eventuosity",
		"APP":"EVENTUOSITY",
		"Entrega":"Aplicativo para organizar eventos desde o planejamento",
		"Diferencial":"O aplicativo conecta as pessoas que fazem parte do projeto. É possível incluir membros, tarefas, prazos e as pessoas podem retroalimentar o evento conforme o escopo de responsabilidade de cada um dos envolvidos.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.eventuosity.com"
	},
	{
		"Categoria":"Evento",
		"Tags":"Eventos, aplicativo, interação, engajamento",
		"País":"EUA",
		"Empresa":"EventBase",
		"APP":"EventBase",
		"Entrega":"A empresa cria aplicativos interativos e fáceis de usar para eventos premium ou de grande complexidade.",
		"Diferencial":"Os aplicativos criados pela EvenBase são utilizados para eventos de grande complexidade ou que exigem uma interatividade muito grande dos participantes durante o evento (e/ou após). Possibilita uma sincronização de dados muito grande atingindo uma alta escala na segurança desses dados.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.eventbase.com"
	},
	{
		"Categoria":"Business",
		"Tags":"Faciliador, aproximador, conteúdo, video, distribuição, awareness, contato",
		"País":"EUA",
		"Empresa":"Distribber",
		"APP":"Distribber",
		"Entrega":"Um facilitador entre os produtores de vídeo e as plataformas digitais de conteúdo.",
		"Diferencial":"O Distribber aproxima os produtores de vídeos e conteúdos das maiores plataformas de streaming, como por exemplo Netflix, iTunes, Amazon, Hulu, Google Play e Cable VOD. Com um formato justo, prometem fazer com que os produtores de vídeo lucrem 100% daquilo que as plataformas pagarem e eles têm apenas uma taxa de serviço.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.distribber.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Marketing, pesquisa",
		"País":"BRA",
		"Empresa":"Dacri Deviati",
		"APP":"Dacri Deviati",
		"Entrega":"Agência de especializada em pesquisa",
		"Diferencial":"Além da pesquisa a agência faz análise de informações que ajudam o desenvolvimento de negócios criativos no Brasil e na América Latina",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.dacrideviati.com"
	},
	{
		"Categoria":"Jogo",
		"Tags":"ensino, investimento, aprendizado, jogo.",
		"País":"EUA",
		"Empresa":"Copper Street",
		"APP":"Copper Street",
		"Entrega":"Simulador para quem quer aprender a investir em Wall Street",
		"Diferencial":"O simulador é todo gamificado para que a pessoa tenha uma melhor experiência ao aprender a investir na bolsa de valores. Ele utiliza dados reais de cotações e variações do mercado para criar uma experiência mais real.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.copperst.com"
	},
	{
		"Categoria":"Social",
		"Tags":"chat, geolocalização",
		"País":"EUA",
		"Empresa":"Chat Scene",
		"APP":"CHAT SCENE",
		"Entrega":"O aplicativo serve para conversar com outras pessoas que estão próximas a você.",
		"Diferencial":"É possível encontrar pessoas que estejam em um raio de 300m de onde você está. Ao localizar alguém, as informações básicas do perfil aparecem na tela para as pessoas se conectarem ou não, de acordo com o interesse de cada um.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.chatscene.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Influenciadores, marketing, target",
		"País":"BRA",
		"Empresa":"Celebryts",
		"APP":"Celebryts",
		"Entrega":"Empresa encontra influencers ideais para negócios",
		"Diferencial":"A empresa é um facilitador da comunicação entre as marcas e os influenciadores ideias para cada tipo de negócio.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.celebryts.com"
	},
	{
		"Categoria":"Marketing",
		"Tags":"Branding, fotos, links, música, network, social, geolicalização, marketing, target, engajamento, awareness",
		"País":"EUA",
		"Empresa":"Bounce Chat",
		"APP":"Bouce Chat",
		"Entrega":"A empresa conecta outras empresas com seu público alvo de várias formas e canais",
		"Diferencial":"Atua em mídia social, networking, fotos, links e música para eventos, hub de mídia, criação de aplicativos, etc. Promove uma interação 360 com o publico alvo",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.bouncechat.com"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"fone de ouvido, utilidade, comunicação, esportes",
		"País":"EUA",
		"Empresa":"Bonx Grip",
		"APP":"Bonx Grip",
		"Entrega":"Um fone de ouvido para atletas que utiliza tecnologia bluetooth conectada à um celular",
		"Diferencial":"O fone foi desenvolvido para o usuário ouvir música, se comunicar com quem está fazendo esporte próximo a ele, receber ligações e se manter conectado",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"https://bonx.co/en/"
	},
	{
		"Categoria":"Base de Dados",
		"Tags":"Conteúdo, VR, video 360, produção de video, conteúdo licenciado, acessibilidade, marketing, facilitador",
		"País":"EUA",
		"Empresa":"Blend Media",
		"APP":"Blend Media",
		"Entrega":"Uma plataforma que serve como o ",
		"Diferencial":"O Blend Media criou uma biblioteca de vídeos em 360o e conteúdo VR para campanhas e licenças além de gerir uma rede global de criadores de video 360. Criaram uma ferramenta para marcas e editores criarem suas próprias experiências no navegador. Oferece também espaços de WebVR personalizáveis que oferecem um formato de anúncio atrativo e compartilhável.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.blend.media"
	},
	{
		"Categoria":"Saúde",
		"Tags":"Prótese, desenvolvimento humano, robótica, inclusão social",
		"País":"EUA",
		"Empresa":"BIONIC",
		"APP":"SUKNEE",
		"Entrega":"Próteses robóticas com preço baixo",
		"Diferencial":"A empresa desenvolve próteses robóticas para pessoas amputadas e também próteses para melhoramento físico, como por exemplo exoesqueletos que podem aumentar a força do usuário, por exemplo.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.bionicm.com"
	},
	{
		"Categoria":"Sustentabilidade",
		"Tags":"Sustentabilidade, plástico, produtos, renovavel, tecnologia, meio ambiente",
		"País":"Indonésia",
		"Empresa":"Avani",
		"APP":"Avani",
		"Entrega":"A empresa faz produtos de plástico ecologicamente correto, sem utilizar petróleo",
		"Diferencial":"A Avani traz soluções integradas trocando o plástico feito a base de petróleo por matéria prima renovável. As principais bases de matéria prima para o produto é o bioplástico de mandioca, fibra de cana de açar e palha de amido de milho.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"www.avanieco.com"
	},
	{
		"Categoria":"Pets",
		"Tags":"advocacia, pet, inclusão social",
		"País":"EUA",
		"Empresa":"Animal Equality",
		"APP":"Animal Equality",
		"Entrega":"Empresa que advoga a favor dos animais através da educação pública, campanhas e investigações.",
		"Diferencial":"Empresa que advoga a favor dos animais através da educação pública, campanhas e investigações.",
		"B2B":"",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"",
		"Site":"www.animalequality.org"
	},
	{
		"Categoria":"Moda",
		"Tags":"Fashion, 3d print, tech",
		"País":"EUA",
		"Empresa":"Feetz",
		"APP":"Feetz",
		"Entrega":"Calçados customizados impressos em 3D",
		"Diferencial":"Os consumidores baixam um App e ",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"https://feetz.com/story"
	},
	{
		"Categoria":"Entretenimento",
		"Tags":"Esporte, Interatividade, IoT",
		"País":"FRA",
		"Empresa":"Foosball Society",
		"APP":"Foosball Society",
		"Entrega":"Plataforma digital para jogar pebolim",
		"Diferencial":"A startup fornece para outras empresas, em regime de comodato, mesas de pebolim conectadas. Os jogadores podem, com seus celulares, armazenar seus resultados e competir com outros jogadores da mesa.",
		"B2B":"X",
		"B2C":"X",
		"Serviços":"X",
		"Produtos":"X",
		"Site":"http://www.foosball-society.com/"
	},
	{
		"Categoria":"Entretenimento",
		"Tags":"Esporte, Entretenimento, Interatividade, Video, Streaming",
		"País":"EUA",
		"Empresa":"Rhinobird",
		"APP":"Rhinobird",
		"Entrega":"Plataforma para compartilhar vídeos multi-ângulo de grandes eventos",
		"Diferencial":"A ferramenta une todos os usuários que capturaram vídeos na mesma localidade e horário e agrupa os conteúdos gerados sobre o mesmo assunto",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"https://rhinobird.tv/"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"VR, projeção, 360",
		"País":"EUA",
		"Empresa":"Magic Planet",
		"APP":"Global Imagination",
		"Entrega":"Projeção 360 graus em globos",
		"Diferencial":"A empresa comercializa globos projetados que emulam a experiência VR. A principal aplicação atual é em educação e museus.",
		"B2B":"X",
		"B2C":"",
		"Serviços":"X",
		"Produtos":"X",
		"Site":"http://globalimagination.com/"
	},
	{
		"Categoria":"Tecnologia",
		"Tags":"VR, 360, 3d",
		"País":"EUA",
		"Empresa":"Vuze Camera",
		"APP":"Vuze",
		"Entrega":"Camera 360 graus 3D",
		"Diferencial":"A empresa se apresenta como a primeira fabricante de câmeras 360 graus com recurso de 3D",
		"B2B":"",
		"B2C":"X",
		"Serviços":"",
		"Produtos":"X",
		"Site":"http://vuze.camera"
	}
}